openapi: 3.2.0
info:
  title: DBaaS Aggregator API version controller API
  version: 6.13.2
  description: This documentation presents the REST API for the "Database as a Service" (DBaaS) component. DBaaS acts as an aggregator for all adapters. It is designed to collect requests for managed databases and route them to the appropriate adapter. DBaaS stores information about all databases used in a cloud project. These databases are isolated by namespace. DBaaS uses a Classifier to identify databases within a cloud namespace. The Classifier includes service-related information such as scope, microservice name, tenant ID, and namespace.
tags:
- name: API version controller
  description: Providing API version info
paths:
  /api-version:
    get:
      tags:
      - API version controller
      responses:
        '200':
          description: Current APi version and supported API versions
          content:
            application/json:
              schema: {}
      summary: Api Version Info
components:
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
