openapi: 3.2.0
info:
  title: DBaaS Aggregator Declarative Controller API
  version: 6.13.2
  description: This documentation presents the REST API for the "Database as a Service" (DBaaS) component.
tags:
- name: Declarative Controller
paths:
  /api/dbaas/declarative/namespaces/{namespace}/service/{serviceName}:
    post:
      deprecated: true
      parameters:
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: serviceName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      summary: Declarative Settings
      tags:
      - Declarative Controller
      security:
      - SecurityScheme:
        - DB_CLIENT
      operationId: postApiDbaasDeclarativeNamespacesByNamespaceServiceByServiceName
      x-operation-id-source: derived
  /api/dbaas/declarative/status/{trackingId}:
    get:
      summary: Operation status
      description: Get operation status by trackingId
      deprecated: true
      parameters:
      - description: Id to track operation
        required: true
        name: trackingId
        in: path
        schema:
          type: string
      responses:
        '200':
          description: Return operation status
          content:
            application/json:
              schema: {}
        '404':
          description: Not found operation status
        '500':
          description: Unknown error which may be related with internal work of DBaaS.
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      tags:
      - Declarative Controller
      security:
      - SecurityScheme:
        - DB_CLIENT
      operationId: getApiDbaasDeclarativeStatusByTrackingId
      x-operation-id-source: derived
components:
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
